# -*- mode: ruby -*-
# vi: set ft=ruby :

$coreos_update_channel = "beta"
$coreos_image_version = "1010.3.0"
$vm_gui = false
$vm_memory = 1024
$vm_cpus = 1

Vagrant.configure(2) do |config|
    config.ssh.insert_key = false
  
    config.vm.box = "coreos-%s" % $coreos_update_channel
    config.vm.box_version = $coreos_image_version
    config.vm.box_url = "http://%s.release.core-os.net/amd64-usr/%s/coreos_production_vagrant.json" % [$coreos_update_channel, $coreos_image_version]

    config.ssh.insert_key = false

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "m2.build-rest.net"

    config.vm.synced_folder ".", "/home/core/vagrant", id: "core", :nfs => true,  :mount_options   => ['nolock,vers=3,udp']

    # expose Docker's TCP port
    config.vm.network "forwarded_port", guest: 2375, host: 2375, auto_correct: true

    # provision cloud-config user-data (configures Docker daemon TCP service)
    config.vm.provision :file, source: "./vagrantfile-user-data", destination: "/tmp/vagrantfile-user-data"
    config.vm.provision :shell, :inline => "mv /tmp/vagrantfile-user-data /var/lib/coreos-vagrant/", :privileged => true

    config.hostsupdater.remove_on_suspend = true;
end
